# Webpage title
title:
  de: Scigility Switzerland AG
  en: Scigility Switzerland AG

# HTML <head> description
description:
  de: Scigility ist der führende Big Data Spezialist in der Schweiz. Wir bieten Consulting, Data Science, Engineering, Training & Support und Legal Counsel an.
  en: Scigility is Switzerland's leading big data specialist solution provider. We offer consulting, data science, engineering, training & support and legal counsel.

defaultlanguage: "de"
enablelanguages: True

# Translatable strings
t:
  en:
    home: Home
    products_services: Products and Services
    company: Company
    contact: Contact
    our_services: Our Services
    more_projects: More Projects
    details: Details
    #position: Position
    top_1st: go
    top_2nd: up

  de:
    home: Home
    products_services: Produkte & Dienstleistungen
    company: Unternehmen
    contact: Kontakt
    our_services: Unsere Dienstleistungen
    more_projects: Kundenprojekte
    other_projects: Weitere Kundenprojekte
    details: Details
    #position: Funktion
    top_1st: Nach
    top_2nd: oben

# Menu
## put here the "ref:" of each page, otherwise the multilang won't work
company_menu:
  - contact
  - team
  - jobs
  - media

# Social accounts

linkedin_url: https://www.linkedin.com/company/scigility
# xing_url:
# twitter_username:
github_username: scigility

# Footer

## "Quick links" section
## put here the "ref:" of each page, otherwise the multilang won't work
quicklinks:
  - team
  - media
  - posts
  - jobs

## "Links" section
footer_links:
  - text: Scigility Big Data Book
    url: http://www.springer.com/de/book/9783658115883
  - text: Swiss Big Data User Group
    url: http://www.meetup.com/de-DE/swiss-big-data/


#############################################################################
#############################################################################
# Misc settings, you shouldn't have to change these
index:
  de: index.de.html
  en: index.en.html

feed:
  en: /feed-en.xml
  de: /feed-de.xml

baseurl: ""
url: ""

# Build settings
markdown: kramdown
kramdown:
input: GFM

collections:
  products:
    output: true
  projects:
    output: true
  jobs:
    output: true
  posts:
#    permalink: /blog/:year/:month/:day/:title/ 
    output: true
  news:
    output: true

analytics: UA-83800555-1
