# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Your awesome title
  fr: Votre titre génial
email: your-email@domain.com
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
#baseurl: "/scigility.com" # the subpath of your site, e.g. /blog
#url: "https://vhf.github.io" # the base hostname & protocol for your site
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  input: GFM

collections:
  products:
    output: true
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false
      author: ""
  -
    scope:
      path: ""
      type: "products"
    values:
      comments: false
      author: ""
  -
    scope:
      path: ""
      type: "projects"
    values:
      comments: false
      author: ""
