# Webpage title
title:
  de: Scigility Switzerland AG
  en: Scigility Switzerland AG
#  fr: Scigility SA
# HTML <head> description, good content means good SEO
description:
  de: Scigility ist der führende Big Data Spezialist in der Schweiz. Wir bieten Consulting, Data Science, Engineering, Trainint & Support und Legal Counsel an.
  en: Scigility is a leading Big Data specialist solution provider. Offering Consulting, Data Science, Engineering, Training & Support and Legal Counsel.
#  fr: Blah blah

defaultlanguage: "de"
enablelanguages: True

# Translatable strings
t:
  en:
    home: Home
    products_services: Products and Services
    company: Company
    contact: Contact
    our_services: Our services
    more_projects: More Projects
    details: Details
    #position: Position
    top_1st: go
    top_2nd: up
#  fr:
#   home: Accueil
#  products_services: Produits et services
#    company: Entreprise
#    contact: Contact
#    our_services: Nos services
#    more_projects: Plus de projets
#    other_projects: Plus de projets
#    details: Details
    #position: Titre
#    top_1st: En
#    top_2nd: Haut
  de:
    home: Home
    products_services: Produkte & Dienstleistungen
    company: Unternehmen
    contact: Kontakt
    our_services: Unsere Dienstleistungen
    more_projects: Kundenprojekte
    other_projects: Weitere Kundenprojekte
    details: Details
    #position: Funktion
    top_1st: Nach
    top_2nd: oben

# Menu
## put here the "ref:" of each page, otherwise the multilang won't work
company_menu:
  - contact
#  - team
  - jobs
  - media

# Social accounts

linkedin_url: https://www.linkedin.com/company/scigility
# googleplus_url:
# facebook_url:
# xing_url:
# zoom_url:
# twitter_username:
github_username: scigility

# Footer

## "Quick links" section
## put here the "ref:" of each page, otherwise the multilang won't work
quicklinks:
#  - team
  - media

## "Links" section
footer_links:
  - text: Scigility Big Data Book
    url: http://www.springer.com/de/book/9783658115883
  - text: Swiss Big Data User Group
    url: http://www.meetup.com/de-DE/swiss-big-data/


#############################################################################
#############################################################################
# Misc settings, you shouldn't have to change these
index:
  de: index.de.html
  en: index.en.html
#  fr: index.fr.html
feed:
  en: /feed-en.xml
#  fr: /feed-fr.xml
  de: /feed-de.xml
baseurl: ""
url: ""

# Build settings
markdown: kramdown
kramdown:
input: GFM

collections:
  products:
    output: true
  projects:
    output: true
  jobs:
    output: true

analytics: UA-83800555-1
